services:
  dataform:
    init: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataform
    volumes:
      - ./:/usr/app/dataform
      - ~/.config/gcloud:/root/.config/gcloud
      # 除外設定
      - /usr/app/dataform/node_modules
