services:
  dataform:
    init: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataform
    volumes:
      - ./:/usr/app/dataform
      - ~/.config/gcloud:/home/node/.config/gcloud_host:ro

volumes:
  gcloud-config-tmp:
